### PR TITLE
fixes #18

### LINKED ISSUE #18: bug in `array_add`
@roa 

see this https://github.com/adjust/pg-numhstore/compare/array_add_fix?expand=1 for an illustration of a bug that results in us having cohorts with 0 valued keys for apps that make no revenue.

Could you please fix that

### PR DESCRIPTION
**Pull request by roa**

### CODE REVIEW

**Comment by rapimo** [comment]
works on mac os but still with compiler warnings

```
src/hstore.h:10:15: warning: redefinition of typedef 'int4' is a C11 feature [-Wtypedef-redefinition]
typedef int32 int4;
              ^
/usr/local/Cellar/postgresql92/9.2.4/include/server/c.h:333:15: note: previous definition is here
typedef int32 int4;
              ^
1 warning generated.
cc -I/usr/local/Cellar/ossp-uuid/1.6.2/include -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv  -I. -I. -I/usr/local/Cellar/postgresql92/9.2.4/include/server -I/usr/local/Cellar/postgresql92/9.2.4/include/internal -I/usr/include/libxml2   -c -o src/array_add.o src/array_add.c
In file included from src/array_add.c:1:
In file included from src/array_add.h:1:
In file included from src/pg_numhstore.h:5:
src/hstore.h:10:15: warning: redefinition of typedef 'int4' is a C11 feature [-Wtypedef-redefinition]
typedef int32 int4;
              ^
/usr/local/Cellar/postgresql92/9.2.4/include/server/c.h:333:15: note: previous definition is here
typedef int32 int4;
              ^
1 warning generated.
cc -I/usr/local/Cellar/ossp-uuid/1.6.2/include -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv  -I. -I. -I/usr/local/Cellar/postgresql92/9.2.4/include/server -I/usr/local/Cellar/postgresql92/9.2.4/include/internal -I/usr/include/libxml2   -c -o src/pg_numhstore.o src/pg_numhstore.c
In file included from src/pg_numhstore.c:1:
In file included from src/pg_numhstore.h:5:
src/hstore.h:10:15: warning: redefinition of typedef 'int4' is a C11 feature [-Wtypedef-redefinition]
typedef int32 int4;
              ^
/usr/local/Cellar/postgresql92/9.2.4/include/server/c.h:333:15: note: previous definition is here
typedef int32 int4;
```

**Comment by roa** [comment]
last commit should fix it

**Comment by rapimo** [comment]
:+1:

**Comment by rapimo** [comment]
travis seems to work too

**Pull request merged**
