### PR TITLE
added array_add function, unified to one lib

### LINKED ISSUE #7: array_count for two dimensional arrays
as array_count for int array is super fast it would be great to have a construct like

``` SQL
array_count(ARRAY[['c','3'],['d','4'],['c','3']])
=> '{c=>6,d=>4}'
```

as this might be a performance improvement over

``` SQL
hstore_add(hstore_add('c=>3'::inthstore,'d=>4'::inthstore),'c=>3'::inthstore)
```

### PR DESCRIPTION
**Pull request by roa**
@rapimo 

fixes #7 

this pull request adds a array_add function:

```
psql (9.2.4)
Type "help" for help.

array=# select array_add(Array['e','c','e']::text[],Array[3,4,3]::integer[]);
     array_add
--------------------
 "c"=>"4", "e"=>"6"
(1 row)
```

also it unifies all previous libs to one lib called _pg_numhstore.so_

please run your tests and let me know, wheather everything works. i need to add some error handling, as this is the first version, but it should(tm) work.

### CODE REVIEW

**Comment by roa** [comment]
of course you need to adjust the sql on your own to the new lib name :)

**Comment by wellle** [comment]
[Just in case if this will become performance critical at some point in time]

If `n` is the total number of keys and `k` the number of distinct keys, then the current approach runs in `O(n log n)`, while it could be improved to `O(n log k)`.

**Comment by roa** [comment]
how and where?

**Comment by roa** [comment]
@rapimo i adjusted the sql, so it uses the new pg_numhstore.so lib

**Comment by rapimo** [comment]
the improvement sugest by @wellle would be really great as in the current use case n is 80.000 and k 300

**Comment by roa** [comment]
okay, i will adapt it tomorrow

**Comment by roa** [comment]
but: as the interface wont change, please add your test cases and / or benchmarks.

**Comment by rapimo** [comment]
yep will do

**Comment by rapimo** [comment]
ok i forgot to specify it but

``` SQL
select array_add(Array['e',NULL,'e']::text[],Array[3,4,3]::integer[]);
=>  {"c"=>"4"}
```

at the moment it segfaults

**Comment by rapimo** [comment]
ok the good news, it's faster,
the bad news it creates wrong results in my test example
and seqfaults (even with non NULLs) in my real world example

ok the test case (somewhat real world'ish)

``` SQL
SELECT 
array_add(array_agg(days_after_install/30 ||'::'|| country || '::' || device_type),array_agg(time_spent))
--SUM(hstore ( days_after_install/30 ||'::'|| country || '::' || device_type, time_spent::text )::inthstore ) 
FROM generate_series(1,100) days_after_install, (VALUES('phone'),('tablet'),('ipod'))devices(device_type),(VALUES('de'),('uk'),('us'),('it'))countries(country),
generate_series(10,600,10) time_spent
```

that should be 549000 for each key starting with 0

it somewhat splits up da shit and create multiple times the same key with different values where the sum is the correct expected value

eg.

```
"0::de::ipod"=>"546030", "0::de::ipod"=>"480", "0::de::ipod"=>"860", "0::de::ipod"=>"830", "0::de::ipod"=>"800",
```

running the above sql multiple times with the same psql connection creates different "splits" so it might be some memory dealloc problem.

but still promising it's 20 times faster than the hstore_add approach (commented out in the above sql)

**Comment by roa** [comment]
ah wait. there is still something weird. investigating :)

**Comment by rapimo** [comment]
I added some test run

```
make installcheck
```

so see what's wrong

**Comment by rapimo** [comment]
looks like the bug is still there
I also get 

compiler error in MacOs

``` bash
src/array_add.c:102:19: error: use of undeclared identifier 'key_len'
        while(i < key_len -1 &&  strcmp(pairs[i].key, pairs[i+1].key ) == 0 )
                  ^
src/array_add.c:108:32: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
        sprintf( value_str, "%ld", current_value );
        ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
                             %d
/usr/include/secure/_stdio.h:49:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
1 warning and 1 error generated.
make: *** [src/array_add.o] Error 1
```

**Comment by roa** [comment]
yes, right. what i pushed was garbage. but i almost fixed all the things you reported. just a little patience :)

**Comment by rapimo** [comment]
no problem 
I think with the installcheck thing we are on a good way :-P

**Comment by rapimo** [comment]
oh and although it's ok to have the input as integer the sum might be long
I added test for that too (still segfaulting)

**Comment by roa** [comment]
latest commit should fix your suggestions

**Comment by roa** [comment]
okay, now all test should pass.

**Comment by wellle** [comment]
If I'm not mistaken the complexity is still `O(n log n)`.

(where `n` is the total number of keys that are not `NULL`)

**Comment by roa** [comment]
yes right. we decided to do further optimizations later. but we should open a new issue, so we wont forget :)

**Pull request merged**
